#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "
ENVIRONMENT
-----------------------------------------------
PUID           | ${PUID}
PGID           | ${PGID}
UMASK          | ${UMASK}
ARGS           | ${ARGS}
-----------------------------------------------
"

groupmod -o -g "${PGID}" abc
usermod -o -u "${PUID}" abc
