#!/usr/bin/with-contenv bash

source /etc/env

echo "Installing rclone..."

mkdir -p /tmp/rclone && \
cd /tmp/rclone && \
rm -rf /tmp/rclone/* && \
curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip && \
unzip rclone-current-linux-amd64.zip && \
cd rclone-*-linux-amd64 && \
cp rclone /usr/bin/ && \
chown root:root /usr/bin/rclone && \
chmod 755 /usr/bin/rclone && \
mkdir -p /usr/local/share/man/man1 && \
cp rclone.1 /usr/local/share/man/man1/ && \
rm -rf /tmp/rclone/* 

echo "rclone install complete..."